min_price = 1
max_price = 200
num_traders = 6
periods = 6
constrained = true

[explicit]
# Fig 3
#costs = [90, 90, 90, 95, 95, 95, 100, 100, 100]
#redemption_values = [135, 135, 135, 95, 95, 95, 90, 90, 90]
costs = []
redemption_values = []

[misc]
num_commodities = 25
timeout = 1
random_seed = 0
quiet = true