min_price = 1
max_price = 200
num_traders = 4
periods = 6
constrained = true

[explicit]
# Fig 3
#costs = [90, 90, 90, 95, 95, 95, 100, 100, 100]
#redemption_values = [135, 135, 135, 95, 95, 95, 90, 90, 90]
costs = []
redemption_values = []

[misc]
num_commodities = 20
timeout = 1
# Set to 0 for no seed
random_seed = 0
quiet = true
# 0 for no graphs
# 1 for supply/demand graph
# 2 for transactions graph
# 3 for both graphs
# 4 for both graphs for both unconstrained and constrained traders
graphs = 4